trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0  # Replace with your build task (e.g., Maven, .NET)
    inputs:
      versionSpec: '16.x'
  
  - script: |
      npm install
      npm run build
      zip -r webapp.zip .  # Create deployable ZIP
    displayName: 'Build & Package'
  
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: 'webapp.zip'
      artifactName: 'webapp'
  
  # Trigger Harness Deployment (via Webhook)
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        $body = @{
          "artifact" = "webapp"
          "version" = "$(Build.BuildId)"
        } | ConvertTo-Json
        Invoke-RestMethod -Uri "https://app.harness.io/gateway/pipeline/api/webhook/custom/..." -Method Post -Body $body -ContentType "application/json"