trigger:
  name: ado_webapp_trigger
  identifier: ado_webapp_trigger
  enabled: true
  orgIdentifier: default
  projectIdentifier: my_project
  pipelineIdentifier: azure_webapp_deployment
  source:
    type: Webhook
    spec:
      type: Custom
      spec:
        payloadConditions:
          - key: artifact
            operator: Equals
            value: "webapp"
        headerConditions: []
  inputYaml: |-
    pipeline:
      identifier: azure_webapp_deployment
      stages:
        - stage:
            identifier: Deploy_to_Azure_Web_App
            type: Deployment
            spec:
              serviceConfig:
                serviceDefinition:
                  spec:
                    artifacts:
                      primary:
                        primaryArtifactRef: <+trigger.artifact>
                        sources:
                          - spec:
                              version: <+trigger.version>